// <auto-generated />
using System;
using CoreSimple.Web.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreSimple.Web.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("CoreSimple.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("LoginName");

                    b.Property<string>("Pwd");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CoreSimple.Models.BillsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("Market");

                    b.Property<string>("ProductNoName");

                    b.Property<int>("ProductNumber");

                    b.Property<string>("Shop");

                    b.HasKey("Id");

                    b.ToTable("BillsItems");
                });

            modelBuilder.Entity("CoreSimple.Models.CashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("CreationTime");

                    b.Property<decimal>("Increase");

                    b.Property<decimal>("Reduce");

                    b.HasKey("Id");

                    b.ToTable("CashFlows");
                });
#pragma warning restore 612, 618
        }
    }
}
